package org.example.explore;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Deque;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import org.example.perm.Derivative;
import org.example.perm.Derivative.Quotient;
import org.example.perm.Derivative.Spectrum;
import org.example.perm.Derivative.Wrap;
import org.example.perm.LatinSquare;
import org.example.perm.Permutation;
import org.example.perm.PermutationSequence;

/**
 * Why do some squares converge and some cycle?
 *
 * <p>The lever is that D commutes with any group homomorphism, since it is built from products and
 * inverses. The sign map S_n -> {±1} is such a homomorphism, so the parity pattern of the rows
 * evolves under classical binary Ducci — which is completely understood. That yields a provable
 * necessary condition for convergence. The finer structure comes from the subgroup generated by the
 * differences: when it is abelian the dynamics are linear and solvable per prime, and when it is a
 * p-group with the sequence length a power of p, convergence is forced.
 */
public final class ConvergenceWhy {

  private ConvergenceWhy() {}

  private static final int LIMIT = 5_000;

  public static void main(String[] args) {
    binaryDucciTable();
    orderFive();
    orderFour();
    abelianPrediction();
    pGroupExhaustive();
  }

  // ---------------------------------------------------------------- mod-m Ducci on plain vectors

  /** One step of classical Ducci: v_i <- v_{i+1} - v_i mod m. */
  static int[] ducciStep(int[] v, int m) {
    int n = v.length;
    int[] next = new int[n];
    for (int i = 0; i < n; i++) {
      next[i] = Math.floorMod(v[(i + 1) % n] - v[i], m);
    }
    return next;
  }

  /** Whether v reaches the zero vector under mod-m Ducci. */
  static boolean ducciConverges(int[] v, int m) {
    Set<String> seen = new HashSet<>();
    int[] state = v.clone();
    while (seen.add(Arrays.toString(state))) {
      if (Arrays.stream(state).allMatch(x -> x == 0)) {
        return true;
      }
      state = ducciStep(state, m);
    }
    return false;
  }

  /** The eventual period of v under mod-m Ducci (1 if it converges to zero). */
  static int ducciPeriod(int[] v, int m) {
    Map<String, Integer> firstSeen = new TreeMap<>();
    int[] state = v.clone();
    for (int step = 0; ; step++) {
      String key = Arrays.toString(state);
      Integer previous = firstSeen.putIfAbsent(key, step);
      if (previous != null) {
        return step - previous;
      }
      state = ducciStep(state, m);
    }
  }

  /** How many of the 2^n binary vectors converge, for each length n. */
  private static void binaryDucciTable() {
    System.out.println("=== binary Ducci: how many of the 2^n parity vectors can die ===");
    for (int n = 2; n <= 8; n++) {
      int converging = 0;
      for (int mask = 0; mask < (1 << n); mask++) {
        int[] v = new int[n];
        for (int i = 0; i < n; i++) {
          v[i] = (mask >> i) & 1;
        }
        if (ducciConverges(v, 2)) {
          converging++;
        }
      }
      System.out.printf(
          "  n=%d   %d / %d%s%n",
          n, converging, 1 << n, Integer.bitCount(n) == 1 ? "   (power of two: all)" : "");
    }
    System.out.println();
  }

  // ------------------------------------------------------------------------------- subgroup tools

  /** The subgroup generated by the given permutations, by closure. */
  static Set<Permutation> generate(List<Permutation> generators, int cap) {
    Set<Permutation> group = new LinkedHashSet<>(generators);
    Deque<Permutation> work = new ArrayDeque<>(generators);
    while (!work.isEmpty() && group.size() <= cap) {
      Permutation g = work.poll();
      for (Permutation h : List.copyOf(group)) {
        for (Permutation product : List.of(g.andThen(h), h.andThen(g), g.inverse())) {
          if (group.add(product)) {
            work.add(product);
          }
        }
      }
    }
    return group;
  }

  static boolean isAbelian(Set<Permutation> group) {
    for (Permutation a : group) {
      for (Permutation b : group) {
        if (!a.andThen(b).equals(b.andThen(a))) {
          return false;
        }
      }
    }
    return true;
  }

  private static int[] signVector(PermutationSequence s) {
    int[] v = new int[s.length()];
    for (int i = 0; i < s.length(); i++) {
      v[i] = s.step(i).sign() > 0 ? 0 : 1;
    }
    return v;
  }

  // ------------------------------------------------------------------------------------ order 5

  private static void orderFive() {
    System.out.println("=== order 5: the sign obstruction and the difference group ===");
    int allEvenConverge = 0;
    int allEvenCycle = 0;
    int mixedConverge = 0;
    int mixedCycle = 0;
    LatinSquare evenButCycling = null;
    Map<Integer, Integer> diffGroupOrderConvergent = new TreeMap<>();
    Map<Integer, Integer> diffGroupOrderCycling = new TreeMap<>();
    Map<Integer, Integer> signPeriodsOfCycling = new TreeMap<>();

    for (LatinSquare square : LatinSquares.withNaturalFirstRow(5)) {
      PermutationSequence rows = square.rowsAsSequence();
      Spectrum spectrum =
          Derivative.spectrum(rows, Wrap.CYCLIC, Quotient.AFTER, LIMIT).orElseThrow();
      boolean converges = spectrum.reachesIdentity();
      boolean allEven = Arrays.stream(signVector(rows)).allMatch(x -> x == 0);

      Set<Permutation> diffGroup =
          generate(Derivative.apply(rows, Wrap.CYCLIC, Quotient.AFTER).steps(), 200);
      (converges ? diffGroupOrderConvergent : diffGroupOrderCycling)
          .merge(diffGroup.size(), 1, Integer::sum);

      if (converges) {
        if (allEven) {
          allEvenConverge++;
        } else {
          mixedConverge++;
        }
      } else {
        signPeriodsOfCycling.merge(ducciPeriod(signVector(rows), 2), 1, Integer::sum);
        if (allEven) {
          allEvenCycle++;
          if (evenButCycling == null) {
            evenButCycling = square;
          }
        } else {
          mixedCycle++;
        }
      }
    }
    System.out.println("                     converges   cycles");
    System.out.printf("  all rows even      %6d      %6d%n", allEvenConverge, allEvenCycle);
    System.out.printf("  mixed parity       %6d      %6d%n", mixedConverge, mixedCycle);
    System.out.println(
        "  difference-group orders, convergent squares: " + diffGroupOrderConvergent);
    System.out.println("  difference-group orders, cycling squares:    " + diffGroupOrderCycling);
    System.out.println("  sign-vector periods of the cycling squares:  " + signPeriodsOfCycling);
    if (evenButCycling != null) {
      System.out.println("  an all-even square that still cycles:");
      System.out.println(indent(evenButCycling.toString()));
      Set<Permutation> g =
          generate(
              Derivative.apply(evenButCycling.rowsAsSequence(), Wrap.CYCLIC, Quotient.AFTER)
                  .steps(),
              200);
      System.out.println(
          "    its differences generate a group of order "
              + g.size()
              + (isAbelian(g) ? " (abelian)" : " (non-abelian)"));
    }
    System.out.println();
  }

  // ------------------------------------------------------------------------------------ order 4

  private static void orderFour() {
    System.out.println(
        "=== order 4: every square converges — what do the differences generate? ===");
    Map<String, Integer> histogram = new TreeMap<>();
    for (LatinSquare square : LatinSquares.withNaturalFirstRow(4)) {
      for (Permutation relabel : Permutations.all(4)) {
        LatinSquare relabelled = org.example.perm.Symmetry.relabelSymbols(square, relabel);
        Set<Permutation> diffGroup =
            generate(
                Derivative.apply(relabelled.rowsAsSequence(), Wrap.CYCLIC, Quotient.AFTER).steps(),
                60);
        String key =
            "order "
                + diffGroup.size()
                + (Integer.bitCount(diffGroup.size()) == 1 ? " (2-group" : " (NOT 2-group")
                + (isAbelian(diffGroup) ? ", abelian)" : ", non-abelian)");
        histogram.merge(key, 1, Integer::sum);
      }
    }
    histogram.forEach((k, v) -> System.out.printf("  %-36s %d%n", k, v));
    System.out.println();
  }

  // -------------------------------------------------------------------- abelian rows, predicted

  /**
   * Rows drawn from Z_6 in every possible order. Exponent arithmetic makes the dynamics linear, so
   * convergence should be decided componentwise: the exponent vector must die under mod-2 Ducci AND
   * under mod-3 Ducci.
   */
  private static void abelianPrediction() {
    System.out.println("=== all 720 orderings of the rows of Z_6: prediction vs reality ===");
    int n = 6;
    int[] shift = new int[n];
    for (int i = 0; i < n; i++) {
      shift[i] = (i + 1) % n;
    }
    Permutation g = Permutation.of(shift);
    List<Permutation> powers = new ArrayList<>();
    Permutation p = Permutation.identity(n);
    for (int i = 0; i < n; i++) {
      powers.add(p);
      p = p.andThen(g);
    }

    int agree = 0;
    int disagree = 0;
    int convergent = 0;
    for (Permutation ordering : Permutations.all(n)) {
      int[] exponents = ordering.toArray(); // row i is g^{exponents[i]}
      List<Permutation> rows = new ArrayList<>();
      int[] mod2 = new int[n];
      int[] mod3 = new int[n];
      for (int i = 0; i < n; i++) {
        rows.add(powers.get(exponents[i]));
        mod2[i] = exponents[i] % 2;
        mod3[i] = exponents[i] % 3;
      }
      boolean predicted = ducciConverges(mod2, 2) && ducciConverges(mod3, 3);
      boolean actual =
          Derivative.spectrum(PermutationSequence.of(rows), Wrap.CYCLIC, Quotient.AFTER, LIMIT)
              .orElseThrow()
              .reachesIdentity();
      if (predicted == actual) {
        agree++;
      } else {
        disagree++;
      }
      if (actual) {
        convergent++;
      }
    }
    System.out.printf(
        "  prediction agrees for %d / 720   (disagreements: %d)   convergent orderings: %d%n%n",
        agree, disagree, convergent);
  }

  // -------------------------------------------------------------------------- p-groups, brute
  // force

  /** Every sequence of length p^k over a p-group should converge; non-p-groups should not. */
  private static void pGroupExhaustive() {
    System.out.println("=== exhaustive Ducci over small groups ===");
    // Dihedral group of the square, order 8, inside S_4.
    Set<Permutation> d4 =
        generate(List.of(Permutation.of(1, 2, 3, 0), Permutation.of(0, 3, 2, 1)), 20);
    exhaust("D4 (order " + d4.size() + "), length 4", List.copyOf(d4), 4);
    // Z_3 inside S_3, length 3.
    Set<Permutation> z3 = generate(List.of(Permutation.of(1, 2, 0)), 10);
    exhaust("Z3 (order " + z3.size() + "), length 3", List.copyOf(z3), 3);
    // All of S_3, length 6: not a p-group — expect failures.
    Set<Permutation> s3 = generate(List.of(Permutation.of(1, 2, 0), Permutation.of(1, 0, 2)), 10);
    exhaust("S3 (order " + s3.size() + "), length 6", List.copyOf(s3), 6);
    // Z_4 inside S_4, length 6: abelian p-group but the LENGTH is wrong — expect failures.
    Set<Permutation> z4 = generate(List.of(Permutation.of(1, 2, 3, 0)), 10);
    exhaust("Z4 (order " + z4.size() + "), length 6", List.copyOf(z4), 6);
  }

  private static void exhaust(String label, List<Permutation> elements, int length) {
    int total = 1;
    for (int i = 0; i < length; i++) {
      total *= elements.size();
    }
    int converging = 0;
    int[] indices = new int[length];
    for (int count = 0; count < total; count++) {
      List<Permutation> terms = new ArrayList<>(length);
      for (int i = 0; i < length; i++) {
        terms.add(elements.get(indices[i]));
      }
      if (Derivative.order(PermutationSequence.of(terms), Wrap.CYCLIC, Quotient.AFTER, LIMIT)
          .isPresent()) {
        converging++;
      }
      for (int i = 0; i < length; i++) { // odometer
        if (++indices[i] < elements.size()) {
          break;
        }
        indices[i] = 0;
      }
    }
    System.out.printf("  %-28s %d / %d converge%n", label, converging, total);
  }

  private static String indent(String text) {
    return "    " + text.replace(System.lineSeparator(), System.lineSeparator() + "    ");
  }
}
