package org.example.explore;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import java.util.TreeMap;
import org.example.perm.Derivative;
import org.example.perm.Derivative.Quotient;
import org.example.perm.Derivative.Wrap;
import org.example.perm.LatinSquare;
import org.example.perm.Permutation;
import org.example.perm.PermutationSequence;

/**
 * The loops themselves, not just their lengths.
 *
 * <p>Two squares with the same period can land on the same attractor, on different attractors that
 * are related by a symmetry, or on genuinely different loops. Two symmetries provably act on
 * attractors: rotating a cyclic sequence commutes with D, and so does conjugating every term by a
 * fixed permutation (both are built from the group operations D respects). So loops are compared
 * raw, up to rotation, and up to rotation plus simultaneous conjugation.
 *
 * <p>Per attractor we also record intrinsic features: the subgroup generated by the terms appearing
 * anywhere in the loop, and the census of cycle types those terms have.
 */
public final class LoopAnatomy {

  private LoopAnatomy() {}

  private static final int LIMIT = 50_000;

  public static void main(String[] args) {
    fiveExhaustive();
    sixSampled(12);
    sixSampled(24);
  }

  // ------------------------------------------------------------------------------ walking to loops

  /** The states of the eventual cycle, in orbit order, starting from the first repeated state. */
  static List<PermutationSequence> cycleStates(PermutationSequence start) {
    Map<PermutationSequence, Integer> firstSeen = new LinkedHashMap<>();
    List<PermutationSequence> trajectory = new ArrayList<>();
    PermutationSequence state = start;
    while (!firstSeen.containsKey(state)) {
      firstSeen.put(state, trajectory.size());
      trajectory.add(state);
      state = Derivative.apply(state, Wrap.CYCLIC, Quotient.AFTER);
      if (trajectory.size() > LIMIT) {
        throw new IllegalStateException("cycle not found within limit");
      }
    }
    return trajectory.subList(firstSeen.get(state), trajectory.size());
  }

  private static String stateString(PermutationSequence s) {
    StringBuilder sb = new StringBuilder();
    for (Permutation p : s.steps()) {
      sb.append(p).append('|');
    }
    return sb.toString();
  }

  /** Canonical form of a loop under rotation of the orbit: least rotation of the state list. */
  static String rotationKey(List<PermutationSequence> cycle) {
    List<String> states = cycle.stream().map(LoopAnatomy::stateString).toList();
    String best = null;
    for (int shift = 0; shift < states.size(); shift++) {
      StringBuilder sb = new StringBuilder();
      for (int i = 0; i < states.size(); i++) {
        sb.append(states.get((shift + i) % states.size())).append('#');
      }
      String candidate = sb.toString();
      if (best == null || candidate.compareTo(best) < 0) {
        best = candidate;
      }
    }
    return best;
  }

  /** Canonical form under rotation and simultaneous conjugation of every term by any h. */
  static String conjugacyKey(List<PermutationSequence> cycle, int n) {
    String best = null;
    for (Permutation h : Permutations.all(n)) {
      List<PermutationSequence> conjugated = new ArrayList<>(cycle.size());
      for (PermutationSequence state : cycle) {
        List<Permutation> terms = new ArrayList<>(state.length());
        for (Permutation p : state.steps()) {
          terms.add(h.inverse().andThen(p).andThen(h));
        }
        conjugated.add(PermutationSequence.of(terms));
      }
      String candidate = rotationKey(conjugated);
      if (best == null || candidate.compareTo(best) < 0) {
        best = candidate;
      }
    }
    return best;
  }

  /** Sorted cycle-type census of all terms appearing anywhere in the loop. */
  static Map<String, Integer> typeCensus(List<PermutationSequence> cycle) {
    Map<String, Integer> census = new TreeMap<>();
    for (PermutationSequence state : cycle) {
      for (Permutation p : state.steps()) {
        List<Integer> lengths = p.cycles().stream().map(c -> c.length).sorted().toList();
        StringBuilder sb = new StringBuilder();
        for (int i = lengths.size() - 1; i >= 0; i--) {
          if (sb.length() > 0) {
            sb.append('+');
          }
          sb.append(lengths.get(i));
        }
        census.merge(sb.toString(), 1, Integer::sum);
      }
    }
    return census;
  }

  private static int loopGroupOrder(List<PermutationSequence> cycle) {
    List<Permutation> terms = new ArrayList<>();
    for (PermutationSequence state : cycle) {
      terms.addAll(state.steps());
    }
    return ConvergenceWhy.generate(terms, 800).size();
  }

  // ----------------------------------------------------------------------------------- order five

  /** All 1200 cycling squares of order 5: how many genuinely different 30-loops exist? */
  private static void fiveExhaustive() {
    System.out.println("=== order 5: the loops behind the 1200 period-30 squares ===");
    Map<String, Integer> rawAttractors = new LinkedHashMap<>();
    Map<String, List<PermutationSequence>> representative = new LinkedHashMap<>();
    for (LatinSquare square : LatinSquares.withNaturalFirstRow(5)) {
      PermutationSequence rows = square.rowsAsSequence();
      var spectrum = Derivative.spectrum(rows, Wrap.CYCLIC, Quotient.AFTER, LIMIT).orElseThrow();
      if (spectrum.reachesIdentity()) {
        continue;
      }
      List<PermutationSequence> cycle = cycleStates(rows);
      String key = rotationKey(cycle);
      rawAttractors.merge(key, 1, Integer::sum);
      representative.putIfAbsent(key, cycle);
    }
    System.out.println("  distinct raw attractors (up to rotation): " + rawAttractors.size());
    System.out.println(
        "  squares landing on each: " + rawAttractors.values().stream().sorted().toList());

    Map<String, List<String>> conjugacyClasses = new LinkedHashMap<>();
    Map<String, Integer> groupOrders = new TreeMap<>();
    Map<String, Map<String, Integer>> censuses = new LinkedHashMap<>();
    for (Map.Entry<String, List<PermutationSequence>> entry : representative.entrySet()) {
      String cKey = conjugacyKey(entry.getValue(), 5);
      conjugacyClasses.computeIfAbsent(cKey, k -> new ArrayList<>()).add(entry.getKey());
      groupOrders.merge("order " + loopGroupOrder(entry.getValue()), 1, Integer::sum);
      censuses.putIfAbsent(cKey, typeCensus(entry.getValue()));
    }
    System.out.println(
        "  up to rotation AND simultaneous conjugation: " + conjugacyClasses.size() + " loop(s)");
    System.out.println(
        "  raw attractors per conjugacy class: "
            + conjugacyClasses.values().stream().map(List::size).sorted().toList());
    System.out.println("  loop-term subgroup orders across attractors: " + groupOrders);
    censuses.forEach(
        (k, census) -> System.out.println("  cycle-type census of one class: " + census));
    System.out.println();
  }

  // ------------------------------------------------------------------------------------ order six

  /** Sampled order-6 squares of one period: are there qualitatively different loops? */
  private static void sixSampled(int targetPeriod) {
    System.out.println("=== order 6, period " + targetPeriod + ": anatomy of the loops ===");
    List<LatinSquare> reservoir = new ArrayList<>(6000);
    Random random = new Random(66L);
    long[] seen = {0};
    LatinSquares.forEachWithNaturalFirstRow(
        6,
        square -> {
          seen[0]++;
          if (reservoir.size() < 6000) {
            reservoir.add(square);
          } else {
            long index = Math.floorMod(random.nextLong(), seen[0]);
            if (index < 6000) {
              reservoir.set((int) index, square);
            }
          }
        });

    Map<String, Integer> rawAttractors = new LinkedHashMap<>();
    Map<String, Integer> loopGroupOfAttractor = new LinkedHashMap<>();
    Map<String, Map<String, Integer>> censusOfAttractor = new LinkedHashMap<>();
    int squares = 0;
    for (LatinSquare square : reservoir) {
      PermutationSequence rows = square.rowsAsSequence();
      var spectrum = Derivative.spectrum(rows, Wrap.CYCLIC, Quotient.AFTER, LIMIT).orElseThrow();
      if (spectrum.reachesIdentity() || spectrum.period() != targetPeriod) {
        continue;
      }
      squares++;
      List<PermutationSequence> cycle = cycleStates(rows);
      String key = rotationKey(cycle);
      rawAttractors.merge(key, 1, Integer::sum);
      if (!loopGroupOfAttractor.containsKey(key)) {
        loopGroupOfAttractor.put(key, loopGroupOrder(cycle));
        censusOfAttractor.put(key, typeCensus(cycle));
      }
    }

    Map<Integer, Integer> attractorsByGroupOrder = new TreeMap<>();
    loopGroupOfAttractor.values().forEach(o -> attractorsByGroupOrder.merge(o, 1, Integer::sum));
    System.out.println("  squares in the sample with this period: " + squares);
    System.out.println("  distinct raw attractors (up to rotation): " + rawAttractors.size());
    System.out.println("  attractors by loop-term subgroup order: " + attractorsByGroupOrder);

    // Show the qualitative split: one census per distinct loop-group order.
    Set<Integer> shown = new java.util.TreeSet<>();
    for (Map.Entry<String, Integer> entry : loopGroupOfAttractor.entrySet()) {
      if (shown.add(entry.getValue())) {
        System.out.println(
            "  a loop with subgroup order "
                + entry.getValue()
                + ": cycle types "
                + censusOfAttractor.get(entry.getKey()));
      }
    }
    System.out.println();
  }
}
